num=10
print(f"num = {num}")
num+=2
print(f"num = {num}")
num-=4
print(f"num = {num}")
num*=6
print(f"num = {num}")
num/=8
print(f"num = {num}")
num%=10
print(f"num = {num}")
num**=8
print(f"num = {num}")
num//=6
print(f"num = {num}")