import numpy as np
Zero=np.array(10)
print(Zero)
print(type(Zero))
print("Dimension :",Zero.ndim)
print("Memory :",Zero.nbytes)
One=np.array([12,24,36,48,60])
print(One)
print(type(One))
print("Dimension :",One.ndim)
print("Memory :",One.nbytes)
Two=np.array([[1,2],[3,4],[5,6],[7,8]])
print(Two)
print(type(Two))
print("Dimension :",Two.ndim)
print("Memory :",Two.nbytes)
Three=np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
print(Three)
print(type(Three))
print("Dimension :",Three.ndim)
print("Memory :",Three.nbytes)