Cartoons=['Tom and Jerry','Doraemon','Shinchan','Chhota Bheem','Motu Patlu']
print("Accessing the list using positive indexing : ")
print(Cartoons[0])
print(Cartoons[1])
print(Cartoons[2])
print(Cartoons[3])
print(Cartoons[4])
print("-------------------------")
print("Accessiing the list using negative indexing : ")
print(Cartoons[-1])
print(Cartoons[-2])
print(Cartoons[-3])
print(Cartoons[-4])
print(Cartoons[-5])