list=[1,2,35,6,8,6,5,8,99,0,66]
print("original list : ",list)
print("---------------------")
list.append(5)
print("after append(5): ",list)
print("---------------------")
list.insert(2,85)
print("after insert(2,85):",list)
print("---------------------")
list.remove(2)
print("after remove(2):",list)
print("---------------------")
list.pop
print("after pop(): ",list)
print("---------------------")
list.pop(list.index(0))
print("after pop(index_of_0) :",list)
print("---------------------")
index_85=list.index(85)
print("after index(85):",index_85)
print("---------------------")
count_2=list.count(2)
print("after count(2):",count_2)
print("---------------------")
list.sort()
print("after sort():",list)
print("---------------------")
list.reverse()
print("after reverse():",list)
print("---------------------")
slice_example = list[:5]
print("slice first 5 elements:",slice_example)
print("---------------------")
list.append(sum(list))
print("after append(sum(list)):",list)
print("---------------------")
list.append(max(list))
print("after append(max(list)) :",list)
print("---------------------")
length=len(list)
print("length of the list :",length)
print("---------------------")
